In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

### Data Collection

In [33]:
df = pd.read_excel(r'/content/piyush analysis.xlsx',skiprows=2)

In [34]:
data = df.iloc[:, :12]

In [35]:
data

f (Hz)            Cp            Rp            C1        ε'  \
0    2.000000e+01  1.698350e-15   19385600000  6.629055e-14  0.025620   
1    2.118510e+01  3.354420e-13   53113000000  6.629055e-14  5.060178   
2    2.244040e+01 -6.366990e-15 -471771000000  6.629055e-14 -0.096047   
3    2.377000e+01  2.429040e-13  -67357300000  6.629055e-14  3.664232   
4    2.517850e+01  8.931880e-14  -47627000000  6.629055e-14  1.347384   
..            ...           ...           ...           ...       ...   
196  1.588660e+06  2.150450e-13      18097500  6.629055e-14  3.243977   
197  1.682790e+06  2.149080e-13      17144900  6.629055e-14  3.241910   
198  1.782500e+06  2.146690e-13      16379000  6.629055e-14  3.238305   
199  1.888120e+06  2.144560e-13      15580300  6.629055e-14  3.235091   
200  2.000000e+06  2.142040e-13      14834200  6.629055e-14  3.231290   

           ε"       σ (S/m)      tan(δ)        M'        M"            Z'  \
0    6.195544  6.886719e-11  241.826515  0.000667  0.161404  1.938527e+10   
1    2.134801  2.513569e-11    0.421883  0.167762  0.070776  8.024985e+09   
2   -0.226896 -2.829830e-12    2.362351 -1.582142 -3.737573 -4.000809e+11   
3   -1.500289 -1.982015e-11   -0.409441  0.233726 -0.095697 -9.670713e+09   
4   -2.003114 -2.803099e-11   -1.486669  0.231195 -0.343711 -3.279079e+10   
..        ...           ...         ...       ...       ...           ...   
196  0.083549  7.376885e-08    0.025755  0.308059  0.007934  1.199647e+04   
197  0.083258  7.786758e-08    0.025682  0.308257  0.007917  1.130042e+04   
198  0.082276  8.150875e-08    0.025407  0.308604  0.007841  1.056611e+04   
199  0.081655  8.568717e-08    0.025240  0.308913  0.007797  9.919567e+03   
200  0.080964  8.999689e-08    0.025056  0.309280  0.007749  9.307410e+03   

              z''  
0    8.016325e+07  
1    1.258952e+11  
2   -1.997041e+11  
3    1.645102e+11  
4    3.203604e+10  
..            ...  
196  7.026207e+08  
197  6.675344e+08  
198  6.446028e+08  
199  6.172134e+08  
200  5.919688e+08  

[201 rows x 12 columns]

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 12 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   f (Hz)   201 non-null    float64
 1   Cp       201 non-null    float64
 2   Rp       201 non-null    int64  
 3   C1       201 non-null    float64
 4   ε'       201 non-null    float64
 5   ε"       201 non-null    float64
 6   σ (S/m)  201 non-null    float64
 7   tan(δ)   201 non-null    float64
 8   M'       201 non-null    float64
 9   M"       201 non-null    float64
 10  Z'       201 non-null    float64
 11  z''      201 non-null    float64
dtypes: float64(11), int64(1)
memory usage: 19.0 KB


In [37]:
data.isnull().sum()

f (Hz)     0
Cp         0
Rp         0
C1         0
ε'         0
ε"         0
σ (S/m)    0
tan(δ)     0
M'         0
M"         0
Z'         0
z''        0
dtype: int64

### For f (Hz)

In [38]:
data['f (Hz)'].unique()

array([2.00000e+01, 2.11851e+01, 2.24404e+01, 2.37700e+01, 2.51785e+01,
       2.66704e+01, 2.82508e+01, 2.99247e+01, 3.16979e+01, 3.35761e+01,
       3.55656e+01, 3.76730e+01, 3.99052e+01, 4.22698e+01, 4.47744e+01,
       4.74275e+01, 5.02377e+01, 5.32145e+01, 5.63677e+01, 5.97077e+01,
       6.32456e+01, 6.69931e+01, 7.09627e+01, 7.51675e+01, 7.96214e+01,
       8.43393e+01, 8.93367e+01, 9.46303e+01, 1.00237e+02, 1.06177e+02,
       1.12468e+02, 1.19132e+02, 1.26191e+02, 1.33669e+02, 1.41589e+02,
       1.49979e+02, 1.58866e+02, 1.68279e+02, 1.78250e+02, 1.88812e+02,
       2.00000e+02, 2.11851e+02, 2.24404e+02, 2.37700e+02, 2.51785e+02,
       2.66704e+02, 2.82508e+02, 2.99247e+02, 3.16979e+02, 3.35761e+02,
       3.55656e+02, 3.76730e+02, 3.99052e+02, 4.22698e+02, 4.47744e+02,
       4.74275e+02, 5.02377e+02, 5.32145e+02, 5.63677e+02, 5.97077e+02,
       6.32456e+02, 6.69931e+02, 7.09627e+02, 7.51675e+02, 7.96214e+02,
       8.43393e+02, 8.93367e+02, 9.46303e+02, 1.00237e+03, 1.061

In [39]:
data['f (Hz)'].duplicated().sum()

np.int64(0)

### For ε'

In [40]:
data["ε'"].unique()

array([ 0.02561979,  5.060178  , -0.09604672,  3.66423249,  1.34738353,
        1.39916014,  3.32282638,  3.28561143, -0.16448045, -1.79826527,
        3.03869842,  4.3568802 ,  0.20110558, -0.63123323,  1.52115188,
        4.096994  ,  0.47070206,  3.845118  ,  2.67756099,  0.28134476,
        3.39104123,  4.55638073,  2.19147363,  5.16877567,  3.12401978,
        4.24245968,  3.33533194,  3.46945361,  3.24872835,  3.87844099,
        4.41349461,  3.81600374,  4.23908061,  4.31776453,  4.16400204,
        3.8718488 ,  4.03668375,  4.04163167,  4.10845869,  3.74830179,
        3.78233379,  3.61534167,  3.49019563,  3.56584744,  3.55853116,
        3.49527931,  3.69935062,  3.65260188,  3.61938448,  3.55414139,
        3.51552352,  3.69132534,  3.66504709,  3.69583579,  3.61522099,
        3.62929539,  3.65284324,  3.60966967,  3.51608167,  3.64009633,
        3.6003169 ,  3.66089869,  3.58578995,  3.59205026,  3.63581216,
        3.56542505,  3.62882775,  3.62120977,  3.60799522,  3.57

In [41]:
data["ε'"].duplicated().sum()

np.int64(0)

### For ε"

In [42]:
data['ε"'].duplicated().sum()

np.int64(0)

### log transform

In [43]:
data['f (Hz)'] = np.log10(data['f (Hz)'])

In [44]:
data.head()

f (Hz)            Cp            Rp            C1        ε'        ε"  \
0  1.301030  1.698350e-15   19385600000  6.629055e-14  0.025620  6.195544   
1  1.326031  3.354420e-13   53113000000  6.629055e-14  5.060178  2.134801   
2  1.351031 -6.366990e-15 -471771000000  6.629055e-14 -0.096047 -0.226896   
3  1.376029  2.429040e-13  -67357300000  6.629055e-14  3.664232 -1.500289   
4  1.401030  8.931880e-14  -47627000000  6.629055e-14  1.347384 -2.003114   

        σ (S/m)      tan(δ)        M'        M"            Z'           z''  
0  6.886719e-11  241.826515  0.000667  0.161404  1.938527e+10  8.016325e+07  
1  2.513569e-11    0.421883  0.167762  0.070776  8.024985e+09  1.258952e+11  
2 -2.829830e-12    2.362351 -1.582142 -3.737573 -4.000809e+11 -1.997041e+11  
3 -1.982015e-11   -0.409441  0.233726 -0.095697 -9.670713e+09  1.645102e+11  
4 -2.803099e-11   -1.486669  0.231195 -0.343711 -3.279079e+10  3.203604e+10

In [68]:
X = data[['f (Hz)']]
Y = data[['ε\'', 'ε"']]

In [69]:
X

f (Hz)
0    1.301030
1    1.326031
2    1.351031
3    1.376029
4    1.401030
..        ...
196  6.201031
197  6.226030
198  6.251030
199  6.276030
200  6.301030

[201 rows x 1 columns]

In [70]:
Y

ε'        ε"
0    0.025620  6.195544
1    5.060178  2.134801
2   -0.096047 -0.226896
3    3.664232 -1.500289
4    1.347384 -2.003114
..        ...       ...
196  3.243977  0.083549
197  3.241910  0.083258
198  3.238305  0.082276
199  3.235091  0.081655
200  3.231290  0.080964

[201 rows x 2 columns]

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

In [72]:
X_train

f (Hz)
137  4.726030
171  5.576030
42   2.351031
119  4.276030
140  4.801030
..        ...
43   2.376029
22   1.851030
72   3.101028
15   1.676030
168  5.501030

[160 rows x 1 columns]

In [73]:
Y_train

ε'        ε"
137  3.443311  0.083597
171  3.326749  0.090022
42   3.490196  0.085104
119  3.491101  0.073505
140  3.433068  0.084975
..        ...       ...
43   3.565847 -0.163370
22   2.191474 -1.165425
72   3.589109  0.003502
15   4.096994  2.241667
168  3.338153  0.089978

[160 rows x 2 columns]

In [74]:
X_train.shape

(160, 1)

In [75]:
Y_train.shape

(160, 2)

In [76]:
print(type(X_train), X_train.shape)
print(type(Y_train), Y_train.shape)


<class 'pandas.core.frame.DataFrame'> (160, 1)
<class 'pandas.core.frame.DataFrame'> (160, 2)


In [77]:
from sklearn.linear_model import Lasso

model = Lasso(alpha = 0.1)

In [78]:
(model.fit(X_train, Y_train))

Lasso(alpha=0.1)

In [80]:
Y_prediction = model.predict(X_test)
Y_prediction

array([[3.40425931, 0.07203937],
       [3.40425931, 0.07203937],
       [3.40425931, 0.07203937],
       [3.40425931, 0.07203937],
       [3.40425931, 0.07203937],
       [3.40425931, 0.07203937],
       [3.40425931, 0.07203937],
       [3.40425931, 0.07203937],
       [3.40425931, 0.07203937],
       [3.40425931, 0.07203937],
       [3.40425931, 0.07203937],
       [3.40425931, 0.07203937],
       [3.40425931, 0.07203937],
       [3.40425931, 0.07203937],
       [3.40425931, 0.07203937],
       [3.40425931, 0.07203937],
       [3.40425931, 0.07203937],
       [3.40425931, 0.07203937],
       [3.40425931, 0.07203937],
       [3.40425931, 0.07203937],
       [3.40425931, 0.07203937],
       [3.40425931, 0.07203937],
       [3.40425931, 0.07203937],
       [3.40425931, 0.07203937],
       [3.40425931, 0.07203937],
       [3.40425931, 0.07203937],
       [3.40425931, 0.07203937],
       [3.40425931, 0.07203937],
       [3.40425931, 0.07203937],
       [3.40425931, 0.07203937],
       [3.

In [83]:
from sklearn.metrics import r2_score

accuracy = r2_score(Y_test, Y_prediction)

In [84]:
print('Accuracy : ',accuracy)

Accuracy :  -0.08470106187921145
